# fly.toml app configuration file generated for xmltojsonconverter-billowing-lake-3303 on 2023-12-10T10:37:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xmltojsonconverter-billowing-lake-3303"
primary_region = "ams"

[build]
  image = "vpetrovss/xmljsonconverter"

[env]
  ASPNETCORE_URLS = "http://+:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
