name: docker-push

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: vpetrovss/xmltojsonconverter:latest
  deploy:
    needs: docker
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup flyctl
        run: |
          echo "Installing flyctl..."
          sudo curl -L https://github.com/superfly/flyctl/releases/latest/download/flyctl_$(uname -s)_$(uname -m) -o /usr/local/bin/flyctl
          sudo chmod +x /usr/local/bin/flyctl

      - name: Deploy to Fly.io
        run: fly deploy --remote-only